In [ ]:
import pandas as pd

In [ ]:
#link of Data.csv- "https://github.com/vaishnavi-jaishwal/Credit-Card-Defaults-Analysis-Dashboard-Power-BI?form=MG0AV3"
data = pd.read_csv('Data.csv')
data.head()

,Unnamed: 0,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X16,X17,X18,X19,X20,X21,X22,X23,Y,state
0,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month,North Carolina
1,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,689,0,0,0,0,1,North Dakota
2,2,120000,2,2,2,26,-1,2,0,0,...,3455,3261,0,1000,1000,1000,0,2000,1,Texas
3,3,90000,2,2,2,34,0,0,0,0,...,14948,15549,1518,1500,1000,1000,1000,5000,0,Illinois
4,4,50000,2,2,1,37,0,0,0,0,...,28959,29547,2000,2019,1200,1100,1069,1000,0,Florida

In [ ]:
data.isnull().sum()

Unnamed: 0    0
X1            0
X2            0
X3            0
X4            0
X5            0
X6            0
X7            0
X8            0
X9            0
X10           0
X11           0
X12           0
X13           0
X14           0
X15           0
X16           0
X17           0
X18           0
X19           0
X20           0
X21           0
X22           0
X23           0
Y             0
state         0
dtype: int64

In [ ]:
data.columns

Index(['Unnamed: 0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9',
       'X10', 'X11', 'X12', 'X13', 'X14', 'X15', 'X16', 'X17', 'X18', 'X19',
       'X20', 'X21', 'X22', 'X23', 'Y', 'state'],
      dtype='object')

In [ ]:
data = pd.read_csv("Data.csv", skiprows = 1)

In [ ]:
data.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month', 'North Carolina'],
      dtype='object')

In [ ]:
data.columns = data.iloc[0]  # Set first row as column names
data = data[1:].reset_index(drop=True)  # Drop the first row and reset index

In [ ]:
data.head()

,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,689,0,0,0,0,1,North Dakota
0,2,120000,2,2,2,26,-1,2,0,0,...,3455,3261,0,1000,1000,1000,0,2000,1,Texas
1,3,90000,2,2,2,34,0,0,0,0,...,14948,15549,1518,1500,1000,1000,1000,5000,0,Illinois
2,4,50000,2,2,1,37,0,0,0,0,...,28959,29547,2000,2019,1200,1100,1069,1000,0,Florida
3,5,50000,1,2,1,57,-1,0,-1,0,...,19146,19131,2000,36681,10000,9000,689,679,0,Alaska
4,6,50000,1,1,2,37,0,0,0,0,...,19619,20024,2500,1815,657,1000,1000,800,0,Georgia

In [ ]:
data.columns = [
    "ID", "LIMIT_BAL", "SEX", "EDUCATION", "MARRIAGE", "AGE",
    "PAY_0", "PAY_2", "PAY_3", "PAY_4", "PAY_5", "PAY_6",
    "BILL_AMT1", "BILL_AMT2", "BILL_AMT3", "BILL_AMT4", "BILL_AMT5", "BILL_AMT6",
    "PAY_AMT1", "PAY_AMT2", "PAY_AMT3", "PAY_AMT4", "PAY_AMT5", "PAY_AMT6",
    "DEFAULT_PAYMENT", "STATE"
]

In [ ]:
data.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT_PAYMENT,STATE
0,2,120000,2,2,2,26,-1,2,0,0,...,3455,3261,0,1000,1000,1000,0,2000,1,Texas
1,3,90000,2,2,2,34,0,0,0,0,...,14948,15549,1518,1500,1000,1000,1000,5000,0,Illinois
2,4,50000,2,2,1,37,0,0,0,0,...,28959,29547,2000,2019,1200,1100,1069,1000,0,Florida
3,5,50000,1,2,1,57,-1,0,-1,0,...,19146,19131,2000,36681,10000,9000,689,679,0,Alaska
4,6,50000,1,1,2,37,0,0,0,0,...,19619,20024,2500,1815,657,1000,1000,800,0,Georgia

In [12]:
data.describe()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT_PAYMENT
count,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,...,29999.000000,29999.000000,29999.000000,29999.000000,2.999900e+04,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000
mean,15001.000000,167489.238975,1.603720,1.853128,1.551885,35.485883,-0.016767,-0.133838,-0.166172,-0.220641,...,43264.391113,40312.744725,38873.056169,5663.769292,5.921338e+03,5225.855695,4826.237741,4799.547618,5215.676423,0.221174
std,8660.109699,129747.029798,0.489132,0.790361,0.521969,9.217819,1.123760,1.197143,1.196878,1.169149,...,64333.443473,60797.723604,59554.677258,16563.524146,2.304123e+04,17607.229085,15666.396081,15278.535203,17777.736580,0.415044
min,2.000000,10000.000000,1.000000,0.000000,0.000000,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,...,-170000.000000,-81334.000000,-339603.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,7501.500000,50000.000000,1.000000,1.000000,1.000000,28.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,2328.000000,1763.500000,1256.000000,1000.000000,8.330000e+02,390.000000,296.000000,253.500000,118.000000,0.000000
50%,15001.000000,140000.000000,2.000000,2.000000,2.000000,34.000000,0.000000,0.000000,0.000000,0.000000,...,19052.000000,18105.000000,17074.000000,2100.000000,2.009000e+03,1800.000000,1500.000000,1500.000000,1500.000000,0.000000
75%,22500.500000,240000.000000,2.000000,2.000000,2.000000,41.000000,0.000000,0.000000,0.000000,0.000000,...,54509.000000,50196.000000,49200.500000,5006.000000,5.000000e+03,4505.000000,4013.500000,4032.000000,4000.000000,0.000000
max,30000.000000,1000000.000000,2.000000,6.000000,3.000000,79.000000,8.000000,8.000000,8.000000,8.000000,...,891586.000000,927171.000000,961664.000000,873552.000000,1.684259e+06,896040.000000,621000.000000,426529.000000,528666.000000,1.000000

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29999 entries, 0 to 29998
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               29999 non-null  int64
 1   LIMIT_BAL        29999 non-null  int64
 2   SEX              29999 non-null  int64
 3   EDUCATION        29999 non-null  int64
 4   MARRIAGE         29999 non-null  int64
 5   AGE              29999 non-null  int64
 6   PAY_0            29999 non-null  int64
 7   PAY_2            29999 non-null  int64
 8   PAY_3            29999 non-null  int64
 9   PAY_4            29999 non-null  int64
 10  PAY_5            29999 non-null  int64
 11  PAY_6            29999 non-null  int64
 12  BILL_AMT1        29999 non-null  int64
 13  BILL_AMT2        29999 non-null  int64
 14  BILL_AMT3        29999 non-null  int64
 15  BILL_AMT4        29999 non-null  int64
 16  BILL_AMT5        29999 non-null  int64
 17  BILL_AMT6        29999 non-null  int64
 18  PAY_AMT1         29999 non-null  int64
 19  PAY_AMT2         29999 non-null  int64
 20  PAY_AMT3         29999 non-null  int64
 21  PAY_AMT4         29999 non-null  int64
 22  PAY_AMT5         29999 non-null  int64
 23  PAY_AMT6         29999 non-null  int64
 24  DEFAULT_PAYMENT  29999 non-null  int64
 25  STATE            29999 non-null  object
dtypes: int64(25), object(1)
memory usage: 6.0+ MB

In [15]:
data.isnull().sum()

ID                 0
LIMIT_BAL          0
SEX                0
EDUCATION          0
MARRIAGE           0
AGE                0
PAY_0              0
PAY_2              0
PAY_3              0
PAY_4              0
PAY_5              0
PAY_6              0
BILL_AMT1          0
BILL_AMT2          0
BILL_AMT3          0
BILL_AMT4          0
BILL_AMT5          0
BILL_AMT6          0
PAY_AMT1           0
PAY_AMT2           0
PAY_AMT3           0
PAY_AMT4           0
PAY_AMT5           0
PAY_AMT6           0
DEFAULT_PAYMENT    0
STATE              0
dtype: int64

In [18]:
import numpy as np

In [23]:
data.columns = data.columns.str.strip()  # Remove leading/trailing spaces

In [25]:
col = "LIMIT_BAL"

# Compute mean & standard deviation
mean = data[col].mean()
std = data[col].std()

# Create Z-score column
data["Z_Score"] = (data[col] - mean) / std

# Show first few rows
data.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT_PAYMENT,STATE,Z-Score,Z_Score
0,2,120000,2,2,2,26,-1,2,0,0,...,0,1000,1000,1000,0,2000,1,Texas,-0.366014,-0.366014
1,3,90000,2,2,2,34,0,0,0,0,...,1518,1500,1000,1000,1000,5000,0,Illinois,-0.597233,-0.597233
2,4,50000,2,2,1,37,0,0,0,0,...,2000,2019,1200,1100,1069,1000,0,Florida,-0.905525,-0.905525
3,5,50000,1,2,1,57,-1,0,-1,0,...,2000,36681,10000,9000,689,679,0,Alaska,-0.905525,-0.905525
4,6,50000,1,1,2,37,0,0,0,0,...,2500,1815,657,1000,1000,800,0,Georgia,-0.905525,-0.905525

In [28]:
outliers = data[(data["Z_Score"] < -3) | (data["Z_Score"] > 3)]

In [35]:
data.shape

(29999, 28)

In [56]:
outliers.count()

ID                 130
LIMIT_BAL          130
SEX                130
EDUCATION          130
MARRIAGE           130
AGE                130
PAY_0              130
PAY_2              130
PAY_3              130
PAY_4              130
PAY_5              130
PAY_6              130
BILL_AMT1          130
BILL_AMT2          130
BILL_AMT3          130
BILL_AMT4          130
BILL_AMT5          130
BILL_AMT6          130
PAY_AMT1           130
PAY_AMT2           130
PAY_AMT3           130
PAY_AMT4           130
PAY_AMT5           130
PAY_AMT6           130
DEFAULT_PAYMENT    130
STATE              130
Z-Score            130
Z_Score            130
dtype: int64

In [63]:
uq = data['STATE'].unique()
len(uq)

50

# **One Hot Encoding if using linearmodel**

In [64]:
HEdf = pd.get_dummies(data, columns=["STATE"], drop_first=True)

In [65]:
HEdf.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,STATE_South Dakota,STATE_Tennessee,STATE_Texas,STATE_Utah,STATE_Vermont,STATE_Virginia,STATE_Washington,STATE_West Virginia,STATE_Wisconsin,STATE_Wyoming
0,2,120000,2,2,2,26,-1,2,0,0,...,False,False,True,False,False,False,False,False,False,False
1,3,90000,2,2,2,34,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
2,4,50000,2,2,1,37,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
3,5,50000,1,2,1,57,-1,0,-1,0,...,False,False,False,False,False,False,False,False,False,False
4,6,50000,1,1,2,37,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False

# **LabelEncoding for Tress base model**

In [128]:
from sklearn.preprocessing import LabelEncoder
LEdf = data.copy()
encoder = LabelEncoder()
LEdf["STATE"] = encoder.fit_transform(data["STATE"])

In [129]:
LEdf.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT_PAYMENT,STATE,Z-Score,Z_Score
0,2,120000,2,2,2,26,-1,2,0,0,...,0,1000,1000,1000,0,2000,1,42,-0.366014,-0.366014
1,3,90000,2,2,2,34,0,0,0,0,...,1518,1500,1000,1000,1000,5000,0,12,-0.597233,-0.597233
2,4,50000,2,2,1,37,0,0,0,0,...,2000,2019,1200,1100,1069,1000,0,8,-0.905525,-0.905525
3,5,50000,1,2,1,57,-1,0,-1,0,...,2000,36681,10000,9000,689,679,0,1,-0.905525,-0.905525
4,6,50000,1,1,2,37,0,0,0,0,...,2500,1815,657,1000,1000,800,0,9,-0.905525,-0.905525

In [131]:
LEdf.columns = LEdf.columns.str.strip()  # Remove spaces from column names

# **Training the Model**

In [39]:
from sklearn.model_selection import train_test_split

In [40]:
y = data['DEFAULT_PAYMENT']

In [74]:
HEdf.columns = HEdf.columns.str.strip()  # Remove spaces from column names

In [75]:
X = HEdf.drop(['Z-Score','ID','DEFAULT_PAYMENT'],axis=1)

In [76]:
X.columns

Index(['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'Z_Score',
       'STATE_Alaska', 'STATE_Arizona', 'STATE_Arkansas', 'STATE_California',
       'STATE_Colorado', 'STATE_Connecticut', 'STATE_Delaware',
       'STATE_Florida', 'STATE_Georgia', 'STATE_Hawaii', 'STATE_Idaho',
       'STATE_Illinois', 'STATE_Indiana', 'STATE_Iowa', 'STATE_Kansas',
       'STATE_Kentucky', 'STATE_Louisiana', 'STATE_Maine', 'STATE_Maryland',
       'STATE_Massachusetts', 'STATE_Michigan', 'STATE_Minnesota',
       'STATE_Mississippi', 'STATE_Missouri', 'STATE_Montana',
       'STATE_Nebraska', 'STATE_Nevada', 'STATE_New Hampshire',
       'STATE_New Jersey', 'STATE_New Mexico', 'STATE_New York',
       'STATE_North Carolina', 'STATE_North Dakota', 'STATE_Ohio',
       'STATE_Oklahoma', 'STATE_Oregon', 'STATE_Pennsylvania',
       'STATE_Rhode Island', 'STATE_South Carolina', 'STATE_South Dakota',
       'STATE_Tennessee', 'STATE_Texas', 'STATE_Utah', 'STATE_Vermont',
       'STATE_Virginia', 'STATE_Washington', 'STATE_West Virginia',
       'STATE_Wisconsin', 'STATE_Wyoming'],
      dtype='object')

In [77]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42)

In [78]:
from sklearn.linear_model import LogisticRegression

In [107]:
model = LogisticRegression(max_iter = 1000)
print(model)

LogisticRegression(max_iter=1000)

In [108]:
model.fit(X_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [109]:
from sklearn.metrics import confusion_matrix,accuracy_score, precision_score, classification_report

In [110]:
y_predic = model.predict(X_test)

In [111]:
conf = confusion_matrix(y_predic,y_test)
conf

array([[5665, 1323],
       [ 166,  346]])

In [112]:
a_score = accuracy_score(y_test,y_predic)
a_score

0.8014666666666667

In [113]:
p_score = precision_score(y_test,y_predic)
p_score

0.67578125

In [114]:
print(classification_report(y_test,y_predic))

              precision    recall  f1-score   support

           0       0.81      0.97      0.88      5831
           1       0.68      0.21      0.32      1669

    accuracy                           0.80      7500
   macro avg       0.74      0.59      0.60      7500
weighted avg       0.78      0.80      0.76      7500